CREATE TABLE `M001UETPMASTER` (
`seq`	INT	 	PRIMARY KEY AUTO_INCREMENT COMMENT 'SEQ',
`isu_kor_nm`	VARCHAR(100)	 	COMMENT 	'종목한글명',
`isu_eng_nm`	VARCHAR(100)	 	COMMENT 	'종목영문명',
`isin_code`	CHAR(12)	 	COMMENT 	'종목코드',
`isu_srt_cd`	CHAR(6)	 	COMMENT 	'단축코드',
`etp_type`	CHAR(3)	 	COMMENT 	'상품구분',
`inst_cd`	CHAR(5)	 	COMMENT 	'발행기관코드',
`req_date`	CHAR(8)	 	COMMENT 	'신청일자',
`list_req_date`	CHAR(8)	 	COMMENT 	'상장신청일자',
`list_date`	CHAR(8)	 	COMMENT 	'상장일자',
`krx_dist_yn`	CHAR(1)	 	COMMENT 	'기초지수KRX분배여부',
`comp_dist_yn`	CHAR(1)	 	COMMENT 	'기초지수발행사분배여부',
`ksd_dist_yn`	CHAR(1)	 	COMMENT 	'기초지수예탁원분배여부',
`mirae_dist_yn`	CHAR(1)	 	COMMENT 	'기초지수미래에셋분배여부',
`idx_inst_cd`	CHAR(4)	 	COMMENT 	'기초지수산출기관코드',
`idx_sym_code`	VARCHAR(16)	 	COMMENT 	'기초지수심볼코드',
`idx_nm`	VARCHAR(100)	 	COMMENT 	'기초지수명',
`idx_dist_inst_cd`	CHAR(4)	 	COMMENT 	'기초지수입수기관코드',
`idx_close_type`	CHAR(2)	 	COMMENT 	'기초지수종가타입',
`idx_holy_cd`	VARCHAR(5)	 	COMMENT 	'기초지수휴장일',
`idx_trace_yd_mult_type`	NUMERIC(2)	 	COMMENT 	'기초지수추적배수구분',
`pre_idx_type`	NUMERIC(2)	 	COMMENT 	'전일기초지수구분(한국시간기준)',
`idx_file_nm`	VARCHAR(512)	 	COMMENT 	'기초지수파일명(경로포함)',
`idx_comp_ksd_dist_yn`	CHAR(1)	 	COMMENT 	'지수구성종목예탁원분배여부',
`idx_comp_mirae_dist_yn`	CHAR(1)	 	COMMENT 	'지수구성종목미래에셋분배여부',
`blom_ticker`	VARCHAR(15)	 	COMMENT 	'블룸버그티커',
`user_req`	VARCHAR(1000)	 	COMMENT 	'종가지수요청사항',
`real_yn`	CHAR(1)	 	COMMENT 	'실시간여부',
`ridx_inst_cd`	CHAR(4)	 	COMMENT 	'실시간지수산출기관코드',
`ridx_dist_inst_cd`	CHAR(4)	 	COMMENT 	'실시간지수입수기관코드',
`ridx_crt_sym_code`	VARCHAR(16)	 	COMMENT 	'실시간지수산출기관심볼코드',
`ridx_dist_sym_code`	VARCHAR(16)	 	COMMENT 	'실시간지수입수기관심볼코드',
`ridx_holy_cd`	VARCHAR(10)	 	COMMENT 	'실시간지수휴장일',
`ridx_krx_dist_yn`	CHAR(1)	 	COMMENT 	'실시간지수KRX분배여부',
`ridx_comp_dist_yn`	CHAR(1)	 	COMMENT 	'실시간지수발행사분배여부',
`ridx_ksd_dist_yn`	CHAR(1)	 	COMMENT 	'실시간지수예탁원분배여부',
`ridx_mirae_dist_yn`	CHAR(1)	 	COMMENT 	'실시간지수미래에셋분배여부',
`ridx_dist_term`	NUMERIC(3)	 	COMMENT 	'실시간지수제공주기',
`refidx_sym_code`	VARCHAR(16)	 	COMMENT 	'참고지수심볼코드',
`refidx_nm`	VARCHAR(100)	 	COMMENT 	'참고지수명',
`refidx_inst_cd`	CHAR(4)	 	COMMENT 	'참고지수입수기관코드',
`refidx_file_nm`	VARCHAR(30)	 	COMMENT 	'참고지수파일명',
`refidx_req`	VARCHAR(1000)	 	COMMENT 	'참고지수요청사항',
`refidx_blom_ticker`	VARCHAR(15)	 	COMMENT 	'참고지수블룸버그티커',
`ex_rate_cd`	CHAR(4)	 	COMMENT 	'적용환율',
`ex_hedge_yn`	CHAR(1)	 	COMMENT 	'환헷지여부',
`isin_stat_cd`	CHAR(4)	 	COMMENT 	'종목상태코드',
`inav_calc_cd`	CHAR(4)	 	COMMENT 	'iNAV/iIV산출구분코드',
`idx_rec_yn`	CHAR(1)	 	COMMENT 	'기초지수입수여부_KOSCOM',
`idx_dis_yn`	CHAR(1)	 	COMMENT 	'기초지수분배여부_KOSCOM',
`inav_calc_yn`	CHAR(1)	 	COMMENT 	'iNAV산출여부_KOSCOM',
`idx_mid`	NUMERIC(3)	 	COMMENT 	'기초지수MID_KOSCOM',
`ridx_mid`	NUMERIC(3)	 	COMMENT 	'실시간지수MID_KOSCOM',
`close_file`	VARCHAR(100)	 	COMMENT 	'종가파일_KOSCOM',
`real_idx_tr`	VARCHAR(100)	 	COMMENT 	'실시간TR_KOSCOM',
`proc_stat`	VARCHAR(300)	 	COMMENT 	'진행상황_KOSCOM',
`insert_id`	VARCHAR(15)	 	COMMENT 	'생성자ID',
`insert_time`	CHAR(12)	 	COMMENT 	'생성시간',
`update_id`	VARCHAR(15)	 	COMMENT 	'수정자ID',
`update_time`	CHAR(12)	 	COMMENT 	'수정시간',
`kor_for_type`	CHAR(1)	COMMENT '국내/해외 구분',
`agent_cd` CHAR(4)	COMMENT '사무수탁사코드 ',
`idx_comp_cd`	CHAR(4)	COMMENT '국내ETP기초지수타입코드 ',
`krx_up_code`	NUMERIC(5)	COMMENT '거래소업종코드 ',
`agent_up_code`	NUMERIC(5)	COMMENT '사무수탁사업종코드 '
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='M001UETPMASTER';
