CREATE TABLE `M000CSKICOMPI` (
`UP_CODE`	NUMERIC(4)	COMMENT 	'업종코드',
`ISIN_CODE`	CHAR(12)	COMMENT 	'종목코드',
`MKT_IDX_TP_CD`	CHAR(1)	COMMENT 	'시장지수구분코드',
`ISU_SRT_CD1`	CHAR(6)	COMMENT 	'단축코드(16013)',
`CALC_FLAG`	NUMERIC(1)	COMMENT 	'업종산출포함유무',
PRIMARY KEY (`UP_CODE`, `ISIN_CODE`, `MKT_IDX_TP_CD`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='M000CSKICOMPI';