CREATE TABLE `M168UIDXMAP` (
`F12506`	NUMERIC(8)	COMMENT 	'일자',
`GUBUN`	CHAR(10)	COMMENT 	'WISEFN/FNGUIDE',
`UP_CODE`	CHAR(6)	COMMENT 	'업종코드',
`ISIN_CODE`	CHAR(12)	COMMENT 	'종목코드',
`CEILING_PERCNT`	NUMERIC(20,12)	COMMENT 	'CEILING비중',
`STYLE_INCLUD_PERCNT`	NUMERIC(20,12)	COMMENT 	'스타일포함비중',
PRIMARY KEY (`F12506`, `GUBUN`, `UP_CODE`, `ISIN_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='M168UIDXMAP';