CREATE TABLE `M001_SKSETFSHRSI` (
`TRADE_DATE`	CHAR(8)	COMMENT 	'일자',
`COMPANY_NO`	NUMERIC(4)	COMMENT 	'사무수탁회사번호',
`ETF_ISIN_CODE`	CHAR(12)	COMMENT 	'ETF표준코드',
`ISSUE_STOCKS`	NUMERIC(10)	COMMENT 	'발행증권수',
`ESTAB_STOCKS`	NUMERIC(10)	COMMENT 	'설정증권수',
`REBUY_STOCKS`	NUMERIC(10)	COMMENT 	'환매증권수',
`LISTED_TYPE`	NUMERIC(2)	COMMENT 	'상장구분',
PRIMARY KEY (`TRADE_DATE`, `COMPANY_NO`, `ETF_ISIN_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='M001_SKSETFSHRSI';